@host=localhost
@port=3000
@comp=web_mariadb
@controller=mariadb_rule


### Try get select all data from animals table
GET http://{{host}}:{{port}}/{{comp}}/{{controller}}/general/selectall HTTP/1.1


### Try get select data from animals table search by name
GET http://{{host}}:{{port}}/{{comp}}/{{controller}}/general/select?name=Panthera%20tigris%20tigris HTTP/1.1
