@host=localhost
@port=3000
@comp=web_sqlite
@controller=http
@category=response

### Try submit build form for web
POST http://{{host}}:{{port}}/{{comp}}/buildform/form/submit_buildform HTTP/1.1
Content-type: application/json

{
  "name": "pdsa_oqc_server",
  "productName": "TESTING Project",
  "homepage": "",
  "version": "1.0.0",
  "engine": "webnodejs",
  "description": "Testing build",
  "author": "VSRND System Team",
  "license": "MIT",
  "components": [
    {
      "name": "oqc",
      "version": "1.0.0",
      "dependencies": {},
      "framework": {
        "oricommjs": "1.2.2"
      },
      "engine": "webbunjs",
      "atomic": {
        "atom": {
          "webdesigner": "1.0.0"
        },
        "molecule": {},
        "organism": {},
        "page": {},
        "template": {}
      }
    }
  ],
  "from": "branches|tags|releases",
  "framework": {
    "oricommjs": "1.2.3"
  },
  "publish": "http://10.89.127.1:22000/deploy/server/",
  "arch": "",
  "os": [
    "alpine",
    "ubuntu"
  ]
}

### Try get build form format
GET http://{{host}}:{{port}}/{{comp}}/{{controller}}/response/json HTTP/1.1

